trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: SonarCloudPrepare@1
  inputs:
     SonarCloud: 'SonarCloud Link'
     organization: 'devopstekka'
     scannerMode: 'MSBuild'
     projectKey: 'OOfDQlJ6IMMp'
     projectName: 'Lazy Load Front'


- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'


- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'